"""Banco curado de Reto Show Familiar: 100 consignas por dificultad."""


def _items(category, difficulty, text):
    return [{"category": category, "difficulty": difficulty, "prompt": prompt.strip()}
            for prompt in text.split("|") if prompt.strip()]


def build_challenges():
    bank = []
    easy = {
        "Imitaciones": "Imitá a un pingüino elegante que llega tarde|Imitá a un gato que pisa algo mojado|Imitá a un robot con poca batería|Imitá a un mono que descubre un espejo|Imitá a un perro pidiendo comida sin ladrar|Imitá a un bebé que prueba limón|Imitá a un detective buscando una media|Imitá a un futbolista festejando un gol absurdo|Imitá a un vampiro con hipo|Imitá a un superhéroe que perdió la capa",
        "Canciones": "Cantá Feliz cumpleaños como cantante de ópera|Cantá Arroz con leche como estrella de rock|Cantá La cucaracha con voz de robot|Cantá una estrofa de Despacito como si tuvieras sueño|Cantá We Will Rock You como presentador de noticias|Cantá Libre soy como un villano|Cantá una canción de cancha en cámara lenta|Cantá una canción infantil con voz de monstruo amable|Cantá el estribillo de una canción de Queen como ratón|Cantá una canción conocida como si estuvieras bajo el agua",
        "Personajes": "Actuá como Superman intentando abrir un frasco|Actuá como Batman buscando sus llaves|Actuá como Harry Potter con una varita que no funciona|Actuá como Darth Vader haciendo una videollamada|Actuá como Shrek en una clase de etiqueta|Actuá como Spider-Man espantando una mosca|Actuá como Elsa con mucho calor|Actuá como Homero Simpson en una dieta|Actuá como Pirata Jack Sparrow en un colectivo|Actuá como Barbie armando un mueble",
        "Físico": "Caminá diez pasos con un libro en la cabeza|Mantenete en un pie y saludá a toda la audiencia|Hacé cinco sentadillas con pose de superhéroe|Caminá como cangrejo alrededor de una silla|Hacé una vuelta lenta sin separar los pies|Tocá rodilla derecha con codo izquierdo seis veces|Hacé ocho pasos diminutos sin perder el equilibrio|Levantate de una silla sin usar las manos|Hacé cuatro saltitos suaves y terminá congelado|Caminá en cámara lenta hasta una pared y volvé",
        "Comedia": "Contá un chiste usando las palabras banana y ascensor|Vendé una cuchara como invento de lujo|Explicá por qué las medias desaparecen en el lavarropas|Dale un discurso de agradecimiento a una papa|Pedile perdón dramáticamente a una silla|Hacé un pronóstico del tiempo para una lluvia de fideos|Presentá a un compañero como campeón mundial de siesta|Inventá una noticia urgente sobre una gallina famosa|Quejate con elegancia porque tu helado imaginario se derritió|Hacé una publicidad de treinta segundos para el aire",
        "Voces": "Decí el abecedario con voz de gigante tímido|Contá hasta diez como una bruja simpática|Pedí un vaso de agua como locutor de fútbol|Decí tu nombre como narrador de película de acción|Describí una banana con voz de documental|Saludá a todos con voz de dibujo animado|Recitá los días de la semana como un rey|Dá una orden sencilla con voz de ardilla|Explicá cómo abrir una puerta con voz de fantasma|Decí tres colores como cantante de tango",
        "Objetos": "Usá una almohada imaginaria como guitarra|Convertí una escoba imaginaria en caballo|Usá una botella como micrófono de estrella|Mostrá cinco usos absurdos para una media|Hacé que una servilleta sea una capa real|Convertí una cuchara en teléfono antiguo|Usá un almohadón como volante de carrera|Hacé una entrevista a un zapato|Transformá una caja imaginaria en mascota|Tocá una batería imaginaria con dos lápices",
        "Improvisación": "Inventá una historia corta con dragón, mate y paraguas|Actuá una llamada entre un gato y un veterinario|Improvisá un saludo de un planeta lejano|Explicá cómo cocinar una nube|Representá a alguien atrapado en un ascensor con un loro|Inventá el final feliz de una película de terror|Pedí indicaciones para llegar a la Luna|Actuá una primera cita entre dos robots|Explicá a un extraterrestre qué es el fútbol|Narrá una carrera entre una tortuga y una tostadora",
        "Coordinación": "Hacé una secuencia de cuatro palmadas para que el equipo la copie|Pasen una mueca de una persona a otra sin hablar|Aplaudan todos juntos sin que nadie cuente|Hagan una ola sentados y luego al revés|Pasen un globo imaginario sin dejarlo caer|Caminen cinco pasos sincronizados|Formen una letra gigante con sus cuerpos|Copien tres poses del participante principal|Inventen un saludo grupal de tres movimientos|Quédense congelados todos al mismo tiempo",
        "Equipo": "Formen una foto de familia real exageradamente feliz|Armen una estatua de un barco en tormenta|Representen juntos una banda de rock|Hagan una escena de gol en el último minuto|Formen un tren humano silencioso|Representen una montaña rusa durante diez segundos|Armen una escultura de un elefante|Actúen como turistas perdidos en su propio salón|Hagan una alfombra roja para un compañero|Representen una orquesta sin instrumentos"
    }
    medium = {
        "Imitaciones": "Imitá a Maradona dando indicaciones para cocinar|Imitá a Messi atendiendo una peluquería|Imitá a Susana Giménez entrevistando a un marciano|Imitá a Ricardo Darín discutiendo con un GPS|Imitá a Shakira enseñando matemáticas|Imitá a Freddie Mercury pidiendo una pizza|Imitá a Rocky Balboa preparándose para lavar platos|Imitá a Mr. Bean en un aeropuerto|Imitá a Chaplin intentando usar un celular|Imitá a un comentarista de fútbol narrando una partida de ajedrez",
        "Canciones": "Cantá el estribillo de De música ligera cambiando todas las vocales por A|Cantá Muchachos como una ópera dramática|Cantá Persiana americana mientras bailás como robot|Cantá Color esperanza con voz de villano|Cantá I Want to Break Free como si contaras un secreto|Cantá La bamba acelerando un poco cada línea|Cantá Un poco loco interpretando dos personajes|Cantá una canción de ABBA como comentarista deportivo|Cantá el estribillo de Livin’ on a Prayer con hipo fingido|Encadená fragmentos de tres canciones conocidas sin detenerte",
        "Personajes": "Actuá como Sherlock Holmes investigando quién comió la última empanada|Actuá como Indiana Jones buscando el control remoto|Actuá como Gandalf prohibiendo entrar al baño|Actuá como Terminator vendiendo flores|Actuá como Cruella de Vil cuidando cachorros|Actuá como El Padrino negociando una porción de torta|Actuá como Wednesday Addams en una fiesta sorpresa|Actuá como el Guasón explicando una receta|Actuá como Yoda dando consejos amorosos|Actuá como Rocky entrenando para ganar un concurso de baile",
        "Físico": "Mantenete en un pie mientras hacés cinco pases de pelota imaginaria|Hacé ocho sentadillas alternando una cara feliz y una triste|Caminá talón con punta alrededor de una silla con un libro en la cabeza|Hacé diez cruces de codo y rodilla siguiendo un ritmo|Sentate y levantate tres veces sin manos y terminá en pose|Hacé una plancha inclinada contra la pared mientras decís los meses al revés|Caminá como oso cuatro pasos y volvé como cangrejo|Sostené una pose de flamenco mientras tarareás una canción|Hacé seis estocadas cortas alternadas como espadachín|Realizá una secuencia segura de salto, giro, palmada y estatua",
        "Comedia": "Improvisá una conferencia de prensa porque sos campeón mundial de perder llaves|Vendé un rollo de papel como tecnología del futuro|Dá una clase seria sobre cómo hablar con mosquitos|Hacé terapia de pareja entre un tenedor y una cuchara|Presentá un documental sobre la vida secreta del control remoto|Defendé ante un juez imaginario a una banana acusada de resbalar gente|Explicá una invasión extraterrestre usando solo términos de cocina|Hacé un tutorial inútil para sentarse en una silla|Entrevistá a tu propia rodilla como celebridad|Narrá una discusión épica entre el frío y el calor",
        "Voces": "Leé un menú imaginario alternando voz de bebé y de gigante|Contá una anécdota cambiando de acento cada frase|Narrá cómo alguien se ata los cordones como final de Mundial|Decí un trabalenguas con voz de robot que se descompone|Hacé un diálogo entre una bruja y un hada cambiando las voces|Explicá las reglas del fútbol como presentador de moda|Recitá una receta como poema romántico|Dá noticias serias con una risa que intentás contener|Describí el salón como guía de safari|Contá hasta veinte alternando voz aguda y grave",
        "Objetos": "Convencé a todos de comprar un zapato que también es teléfono|Usá tres objetos imaginarios en una escena de espionaje|Transformá una silla en auto de carreras sin moverla|Hacé una escena romántica con una escoba imaginaria|Mostrá seis funciones imposibles de un repasador|Usá un almohadón como cinco instrumentos distintos|Construí una máquina imaginaria y explicá cómo funciona|Representá una pelea de película usando solo una servilleta|Convertí una botella vacía en premio internacional|Hacé malabares imaginarios con objetos de distinto peso",
        "Improvisación": "Creá una escena que incluya un rey, un delivery y un dinosaurio|Improvisá una discusión entre vos y tu reflejo rebelde|Actuá un minuto como turista del futuro en 2026|Inventá una telenovela sobre una empanada desaparecida|Representá una entrevista laboral para ser superhéroe|Improvisá un juicio donde el acusado es el despertador|Contá una historia que empiece con boda y termine en nave espacial|Actuá una llamada de emergencia porque tu sombra se escapó|Creá un comercial de vacaciones en Marte|Improvisá una clase de baile para pingüinos",
        "Coordinación": "Creá seis movimientos rítmicos y hacé que el equipo los repita en orden|Pasen dos ritmos distintos por la ronda sin mezclarlos|Hagan una ola doble sin hablar|Caminen sincronizados y cambien de dirección con una mirada|Copien una secuencia de palmas, muslos, chasquido y pose|Formen tres figuras grupales distintas sin hablar|Pasen una pelota imaginaria que cambia de tamaño|Mantengan un pulso de palmadas mientras uno canta|Hagan espejo por parejas durante veinte segundos|Construyan una máquina humana con movimiento y sonido",
        "Equipo": "Representen una escena de aeropuerto con tormenta|Armen una foto de casamiento donde todos ocultan un secreto|Actúen como una familia de superhéroes desayunando|Representen una expedición que descubre una media gigante|Hagan una escena muda de restaurante desastroso|Formen un reloj humano que marque tres horas distintas|Improvisen una banda musical que pierde el ritmo y se recupera|Actúen como pasajeros de un barco en una ola enorme|Representen una carrera en cámara súper lenta|Armen un tráiler de película de acción familiar"
    }
    hard = {
        "Imitaciones": "Imitá consecutivamente a Messi, Maradona y un relator sin anunciar los cambios|Imitá a cinco animales encadenados para que el público los reconozca|Imitá a un político dando un discurso mientras se convierte lentamente en robot|Imitá a Freddie Mercury, Elvis y Michael Jackson en un mismo concierto|Imitá a tres miembros de tu familia sin decir sus nombres|Imitá a un chef famoso cocinando durante un terremoto imaginario|Imitá a cuatro emociones sin palabras y sin repetir gestos|Imitá una película completa usando solo seis movimientos|Imitá a un director de orquesta controlando una tormenta|Imitá a un comentarista que narra simultáneamente fútbol y tenis",
        "Canciones": "Cantá fragmentos reconocibles de cuatro canciones sin pausa|Cantá De música ligera primero como tango y luego como ópera|Cantá una canción conocida mientras el equipo marca un ritmo diferente|Improvisá una canción que incluya los nombres de todo tu equipo|Cantá tres estribillos famosos usando una sola vocal|Convertí una canción infantil en rock, cumbia y balada|Cantá Bohemian Rhapsody representando tres voces distintas|Inventá una letra sobre el salón usando la melodía de Feliz cumpleaños|Cantá una canción al revés en emociones: empezá feliz y terminá dramático|Armá un popurrí reconocible de canciones de tres décadas",
        "Personajes": "Actuá como Darth Vader y Yoda discutiendo por el control remoto|Actuá una entrevista entre Batman y el Guasón cambiando de personaje|Representá a Harry Potter, Voldemort y Dobby en una escena de cocina|Actuá como cuatro superhéroes atrapados en un ascensor|Interpretá a Homero, Marge y Bart planeando unas vacaciones|Actuá como Sherlock Holmes interrogando a Jack Sparrow|Representá a Rocky y Terminator compitiendo en un programa de cocina|Actuá como Elsa y Shrek intentando compartir departamento|Interpretá a Chaplin en una escena moderna sin emitir sonidos|Actuá a un villano que intenta ser bueno pero no sabe cómo",
        "Físico": "Mantené equilibrio en un pie y hacé diez cruces lentos de brazos sin apoyarte|Completá una secuencia de diez sentadillas, palmadas alternadas y poses|Caminá talón con punta alrededor de dos sillas y regresá en cámara lenta|Hacé una rutina segura de oso, cangrejo y estatua sin detenerte|Levantate y sentate cinco veces sin manos sosteniendo un libro en la cabeza|Coordiná doce toques alternados de codo y rodilla siguiendo palmadas|Mantené una sentadilla suave mientras nombrás diez países|Hacé una coreografía de ocho movimientos y repetila en orden inverso|Pasá del suelo a estar de pie sin manos y terminá en equilibrio|Completá una secuencia segura de equilibrio, giro, estocada y salto suave tres veces",
        "Comedia": "Dá una charla motivacional para objetos que nadie encuentra|Defendé durante un minuto que dormir es un deporte olímpico|Improvisá un debate entre un fantasma escéptico y un cazafantasmas miedoso|Hacé un noticiero con tres noticias que empeoran de manera absurda|Vendé una piedra común usando lujo, ciencia y emoción|Representá una cita romántica entre el Wi‑Fi y una contraseña|Dá una clase magistral sobre llegar tarde puntualmente|Actuá un juicio contra el lunes con fiscal, defensa y acusado|Explicá seriamente por qué los pingüinos deberían gobernar el mundo|Improvisá una entrega de premios donde ganaste por no hacer nada",
        "Voces": "Contá una historia con cinco personajes y una voz distinta para cada uno|Narrá una persecución alternando relator, villano y héroe|Decí un trabalenguas cambiando de emoción en cada palabra|Hacé un debate entre tres animales sin perder sus voces|Improvisá una radio completa: conductor, móvil, invitado y publicidad|Relatá una receta alternando ópera, susurro y relato deportivo|Contá un cuento acelerando gradualmente sin perder claridad|Interpretá una discusión entre tu voz interior y tu voz exterior|Doblá una escena imaginaria con cuatro personajes|Narrá el salón como documental dramático y comedia a la vez",
        "Objetos": "Creá una escena coherente usando una silla como cinco objetos distintos|Inventá y demostrá una máquina con cuatro objetos imaginarios|Hacé una película de acción donde el héroe es una media|Vendé tres objetos comunes como un único producto revolucionario|Representá un viaje completo usando solo un almohadón|Construí una criatura imaginaria con objetos del salón sin moverlos|Mostrá ocho usos absurdos y distintos para una cuchara|Improvisá un truco de magia fallido que termina exitosamente|Convertí una botella en tres personajes de una historia|Representá una tormenta, un barco y un rescate usando una servilleta",
        "Improvisación": "Improvisá una historia con cinco palabras elegidas por el equipo|Actuá una escena que pase de terror a romance y termine en comedia|Creá un cuento donde cada frase empiece con la siguiente letra del alfabeto|Improvisá una entrevista cambiando entre entrevistador e invitado|Representá un viaje temporal con tres épocas claramente diferentes|Contá una historia sin usar la letra A|Actuá una escena que incluya un secreto, una alarma y un final musical|Improvisá un minuto sin hablar usando tres emociones elegidas por rivales|Creá una telenovela completa con presentación, conflicto y final|Representá una película inventada a velocidad normal, rápida y lenta",
        "Coordinación": "Enseñá al equipo una secuencia de diez movimientos y háganla juntos|Mantengan dos ritmos simultáneos mientras una persona canta|Hagan una ola triple que cambie de dirección sin hablar|Pasen tres objetos imaginarios de pesos distintos sin confundirlos|Construyan una máquina humana que acelere y se detenga junta|Repitan una secuencia de ocho sonidos y gestos en orden inverso|Formen cuatro figuras grupales en diez segundos cada una|Hagan espejo en parejas mientras cambian líder sin avisar|Mantengan un ritmo y congélense cada vez que el anfitrión levante la mano|Creen una coreografía grupal y repítanla al doble de velocidad",
        "Equipo": "Improvisen una película muda con héroe, villano y giro final|Representen una familia cenando durante una invasión alienígena|Armen una banda y toquen una canción reconocible sin instrumentos|Actúen un rescate épico de un control remoto perdido|Representen un Mundial entero en treinta segundos|Creen un comercial donde todos hablen pero nunca al mismo tiempo|Improvisen un restaurante con chef, mozo, cliente y crítico|Representen una montaña rusa que se transforma en nave espacial|Hagan un noticiero grupal con móvil en vivo y publicidad|Creen una escena cómica donde cada integrante tenga una emoción distinta"
    }
    for difficulty, groups in (("facil", easy), ("medio", medium), ("dificil", hard)):
        for category, prompts in groups.items():
            bank.extend(_items(category, difficulty, prompts))
    return bank
